# Generated by Django 3.1.2 on 2020-10-27 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201022_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 10, 0, 5, 245623, tzinfo=utc)),
        ),
    ]
