# Generated by Django 3.1.2 on 2020-11-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201027_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tr',
            field=models.TextField(default='django.db.models.fields.CharField', editable=False),
        ),
    ]
