# Generated by Django 3.1.2 on 2020-10-21 10:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=100)),
                ('publishedDate', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 29, 25, 402359, tzinfo=utc))),
                ('difficulty', models.FloatField()),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
